package com.addressbook.api.application.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@Table(name = "address_book")
@NamedQueries({
    @NamedQuery(name = "com.addressbook.dao.AddressBookDAO.findAll",
            query = "from Student"),
    
    @NamedQuery(name = "com.addressbook.dao.AddressBookDAO.findByName",
            query = "from Student s "
            + "where s.firstName like :name "
            + "or s.lastName like :name")
})
public class Student {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "first_name")
    private String firstName;
 
    @Column(name = "last_name")
    private String lastName;

    @Column(name = "phone_number")
    private String phone;
    
    @Column(name = "email")
    private String email;
    
    public Student() {
    }
    
    /**
     * A constructor to create students. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public Student(String firstName, String lastName, String phone, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.email = email;
    }
}
