package com.addressbook.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import org.joda.time.DateTime;

@Entity
@Table(name = "address_book")
@NamedQueries({
        @NamedQuery(
                name = "com.addressbook.api.application.pojo.Student.findAll",
                query = "select s from Student s"
        ),
        @NamedQuery(
        		name = "com.addressbook.api.application.pojo.Student.findByName",
        		query = "select s from Student s "
        		+ "where s.firstName like :name "
        		+ "or s.lastName like :name"),
        @NamedQuery(
        		name = "com.addressbook.api.application.pojo.Student.findByParent",
        		query = "select s from Student s "
        		+ "where s.parents like :parent"),
        @NamedQuery(
        		name = "com.addressbook.api.application.pojo.Student.findByGrade",
        		query = "select s from Student s "
        		+ "where s.grade = :grade")

		})

public class Student {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "first_name", nullable = false)
    private String firstName;
 
    @Column(name = "last_name", nullable = false)
    private String lastName;

    @Column(name = "phone_number")
    private String phone;
    
    @Column(name = "email")
    private String email;
    
    @Column(name = "grade")
    private int grade;
    
    @Column(name = "parents_guardians")
    private String parents;
    
    @Column(name = "address")
    private String address;
    
    @Column(name = "state")
    private String state;
    
    @Column(name = "city")
    private String city;
    
    @Column(name = "zip_code")
    private int zipCode;
    
    @Column(name = "created")
    private DateTime created;
    
    @Column(name = "updated")
    private DateTime updated;
    
    public Student() {
    }
    
    /**
     * A constructor to create students. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public Student(String firstName, 
    		       String lastName, 
    		       String phone, 
    		       String email,
    		       int grade,
    		       String parents,
    		       String address,
    		       String state,
    		       String city,
    		       int zipCode,
    		       DateTime created,
    		       DateTime updated) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.email = email;
        this.grade = grade;
        this.parents = parents;
        this.address = address;
        this.state = state;
        this.city = city;
        this.zipCode = zipCode;
        this.created = created;
        this.updated = updated;
    }
    
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }
    
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String getLastName(){
    	return lastName;
    }
    
    public void setLastName(String lastName){
    	this.lastName = lastName;
    }
    
    public String getPhone(){
    	return phone;
    }
    
    public void setPhone(String phone){
    	this.phone = phone;
    }
    
    public String getEmail(){
    	return email;
    }
    
    public void setEmail(String email){
    	this.email = email;
    }
    
    public int getGrade(){
    	return grade;
    }
    
    public void setGrade(int grade){
    	this.grade = grade;
    }
    
    public String getParents(){
    	return parents;
    }
    
    public void setParents(String parents){
    	this.parents = parents;
    }
    
    public String getAddress(){
    	return address;
    }
    
    public void setAddress(String address){
    	this.address = address;
    }
    
    public String state(){
    	return state;
    }
    
    public void setState(String state){
    	this.state = state;
    }
    
    public String getCity(){
    	return city;
    }
    
    public void setCity(String city){
    	this.city = city;
    }
    
    public int getZipCode(){
    	return zipCode;
    }
    
    public void setZipCode(int zipCode){
    	this.zipCode = zipCode;
    }
}







